name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    env:
      DOCKER_REGISTRY: public.ecr.aws/moneymeets/openapi-generator
      TAG: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: docker build -t $DOCKER_REGISTRY:$TAG .

      - id: login-ecr-public
        if: github.ref == 'refs/heads/moneymeets-typescript-angular'
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - if: github.ref == 'refs/heads/moneymeets-typescript-angular'
        run: docker push $DOCKER_REGISTRY:$TAG
